name: Upload to PyPI
on:
  push:
    paths:
      - "src/**"
      - "setup.py"
      - "pyproject.toml"
  workflow_dispatch:
  repository_dispatch:

jobs:

  # only increment on master
  bumpversion:
    name: auto increment version
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - run: |
          pip3 install --upgrade bump2version
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          bump2version --config-file .bumpversion.cfg minor
          git add -A
          git push
          git push --tags

  build:

    name: Build on ${{ matrix.cpu }}
    runs-on: ubuntu-latest
    needs: [bumpversion]
    strategy:
      matrix:
        base_image: ["raspios_lite:latest"]
        cpu: [arm1176, cortex-a7, cortex-a8, cortex-a53]

    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    
    - name: Build RPI environment
      uses: pguyot/arm-runner-action@v2.5.2
      with:
        commands: src/gh-actions-rpi-cmd.sh
        base_image: ${{ matrix.base_image }}
        image_additional_mb: 10000
        cpu: ${{ matrix.cpu }}
        optimize_image: false
        shell: /bin/bash
        exit_on_fail: false
        debug: true
        copy_artifact_path: dist/
        copy_artifact_dest: .

    # only publish if master branch
    - name: Publish distribution 📦 to PyPI
      if: success() && github.ref == 'refs/heads/master'
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip_existing: true
        verbose: true
